apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-overlay-threshold-serviceaccount
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubernetes-overlay-threshold-clusterrole
  namespace: monitoring
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get","list","watch","delete"]
  - apiGroups: ["*"]
    resources: ["events"]
    verbs: ["create","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-overlay-threshold-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-overlay-threshold-clusterrole
subjects:
- kind: ServiceAccount
  name: kubernetes-overlay-threshold-serviceaccount
  namespace: monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubernetes-overlay-threshold
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: kubernetes-overlay-threshold
  template:
    metadata:
      labels:
        name: kubernetes-overlay-threshold
    spec:
      serviceAccount: kubernetes-overlay-threshold-serviceaccount
      serviceAccountName: kubernetes-overlay-threshold-serviceaccount
      tolerations:
        - operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: NotIn
                values:
                - windows
      containers:
      - name: kubernetes-overlay-threshold
        image: mcfly722/kubernetes-overlay-threshold:latest
        command:
          - /kubernetes-overlay-threshold
        args: ["-sleepIntervalSec","123","-dockerPath","/var/lib/docker","-overlayThresholdMB","4096","-maxFilesThreshold","1048576"]
        env:
        resources:
          limits:
            cpu: 30m
            memory: 50Mi
          requests:
            cpu: 30m
            memory: 50Mi
        volumeMounts:
        - mountPath: /var/lib/docker
          name: docker-path
          readOnly: true
      volumes:
      - name: docker-path
        hostPath:
          path: /var/lib/docker
          type: Directory       